# Path to where Vale stores downloaded style packages
StylesPath = .vale/styles

# Set the minimum alert level to report: suggestion, warning, or error
MinAlertLevel = suggestion

# List external packages to automatically download
Packages = Microsoft, write-good, alex, Readability

# Scope configuration to specific document types
[*.{md, mdx, txt}]
# Enable Vale's built-in rules alongside the downloaded Style Guides
BasedOnStyles = Vale, Microsoft, write-good, alex, Readability